/**:
  ros__parameters:
    muscle_embodiment: "LIBERO_PANDA"
    camera_config: "wrist_cam"
    camera_topic: "/synapse/camera/image_raw"

synapse_bt_node:
  ros__parameters:
    bt_tick_frequency_hz: 50
    obs_buffer_window_size: 20
    brain_option: "MANUAL"
    muscle_option: "DUMMY"

manual_adapter:
  ros__parameters:
    robot_description: True
    description_name: "panda_description"
    eef_frame: "panda_hand"
