default:
  obs_buffer_window_size: 20
  bt_tick_frequency_hz: 50
  brain_option: "MANUAL"
  muscle_option: "DUMMY"
  embodiment_name: "SINGLE_PANDA_CAM"
  # embodiment_name: "SINGLE_FR5"
  brain_registry:
    - "manual:MANUAL"
  publish_rate_hz: 100


gr00t_franka_test:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_PANDA_CAM"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "GR00T"
  muscle_option: "DUMMY"
  brain_registry:
    - "vla_franka:GR00T"
  # gr00t
  vla_franka:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  publish_rate_hz: 100

  robot_description: True
  description_name: "panda_description"
  eef_frame: "panda_hand"

gr00t_franka_sim:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_PANDA_CAM"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "GR00T"
  muscle_option: "ISAAC"

  brain_registry:
    - "vla_franka:GR00T"
  vla_franka:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  # isaac sim
  publish_rate_hz: 100

fairino_manual_sim:
  # basic
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_FR5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "MANUAL"
  muscle_option: "ISAAC"

  brain_registry:
    - "manual_adapter:MANUAL"
  # isaac sim
  publish_rate_hz: 100


multi_brain_test:
  # basic
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_PANDA_CAM"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20

  muscle_option: "ISAAC"
  brain_option: "GR00T"

  # brain
  brain_registry:
    - "manual_adapter:MANUAL"
    - "vla_pick:GR00T"
    - "vla_place:GR00T"

  ## vla_pick
  vla_pick:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  vla_place:
    policy_ip: "172.16.6.101"
    policy_port: "8889"
    default_command: "place the box on the tray"

  publish_rate_hz: 100

dual_arm_multi_brain:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "DUAL_PANDA"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20

  muscle_option: "ISAAC"
  brain_option: "GR00T"

  brain_registry:
    - "manual_adapter:MANUAL"
    - "vla_left:GR00T"

  vla_left:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  publish_rate_hz: 100

dual_armhand_manual:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "DUAL_PANDA_V5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "ISAAC"
  # muscle_option: "DUMMY"
  brain_option: "MANUAL"

  brain_registry:
    - "manual_adapter:MANUAL"

  publish_rate_hz: 100

fr5_real:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_FR5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "REAL_ROBOT"
  brain_option: "MANUAL"

  brain_registry:
    - "manual_adapter:MANUAL"

  publish_rate_hz: 100
  
single_armhand:
  scenario_filename: "scn_pilot.yaml"
  embodiment_name: "SINGLE_PANDAV4"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "ISAAC"
  brain_option: "MANUAL"

  brain_registry:
    - "manual_adapter:MANUAL"

  publish_rate_hz: 100