default:
  # basic information
  obs_buffer_window_size: 20
  bt_tick_frequency_hz: 50
  brain_option: "MANUAL"
  muscle_option: "DUMMY"
  muscle_embodiment: "LIBERO_PANDA"
  # muscle information
  robot_description: True
  description_name: "panda_description"
  eef_frame: "panda_hand"
  # dummy
  publish_rate_hz: 100


gr00t_franka_test:
  # basic
  muscle_embodiment: "LIBERO_PANDA"
  camera_config: "wrist_cam"
  camera_topic: "/synapse/camera/image_raw"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "GR00T"
  muscle_option: "DUMMY"
  # gr00t
  robot_description: True
  description_name: "panda_description"
  eef_frame: "panda_hand"
  policy_ip: "172.16.6.101"
  policy_port: "8888"
  # dummy
  publish_rate_hz: 100

gr00t_franka_sim:
  # basic
  muscle_embodiment: "LIBERO_PANDA"
  camera_config: "wrist_cam"
  camera_topic: "/synapse/camera/image_raw"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "GR00T"
  muscle_option: "ISAAC"
  # gr00t
  robot_description: True
  description_name: "panda_description"
  eef_frame: "panda_hand"
  policy_ip: "172.16.6.101"
  policy_port: "8888"
  # isaac sim
  publish_rate_hz: 100
  usd_path: "/home/rog-sf/ws/synapse_ws/src/synapse/resources/OXE.usd"
  robot_name: "panda"
  robot_prim_path: "/World/franka_set/Franka/panda"

fairino_manual_sim:
  # basic
  muscle_embodiment: "FAIRINO_FR5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  brain_option: "MANUAL"
  muscle_option: "ISAAC"
  # manual
  robot_description: False
  urdf_path: "/home/rog-sf/ws/synapse_ws/src/synapse/resources/fairino5_v6.urdf"
  eef_frame: "wrist3_link"
  # isaac sim
  publish_rate_hz: 100
  usd_path: "/home/rog-sf/ws/synapse_ws/src/synapse/resources/fairino5_v6.usd"
  robot_name: "fairino5_v6_robot"
  robot_prim_path: "/World/fairino5_v6_robot"