default:
  obs_buffer_window_size: 20
  bt_tick_frequency_hz: 50
  muscle_option: "DUMMY"
  embodiment_name: "SINGLE_PANDA_CAM"
  brain_registry:
    - "manual:MANUAL"
  publish_rate_hz: 100

fairino:
  # basic
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "SINGLE_FR5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "ISAAC"

  brain_registry:
    - "manual_adapter:MANUAL"
  publish_rate_hz: 100

bottle_opener:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "DUAL_XARM_V5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  # muscle_option: "ISAAC"
  muscle_option: "REAL_ROBOT"
  move_time_sec: 0.01       # mandatory setting for REAL_ROBOT
  min_move_time_sec: 0.01   # mandatory setting for REAL_ROBOT

  brain_registry:
    - "manual_adapter:MANUAL"
    - "random_brain_adapter:RANDOM"
    - "rosbag_player:ROSBAG"

  rosbag_player:
    bag_path: "/home/rog-sf/ws/synapse_ws/src/synapse/resources/snack1.json"
    topic_component_map:
      - "/xarm7_left_controller/commands:left_arm"
      - "/xarm7_right_controller/commands:right_arm"
      - "/allegro_hand_position_effort_controller_l/commands:left_hand"
      - "/allegro_hand_position_effort_controller_r/commands:right_hand"
    seek_velocity: 0.2
    seek_min_duration: 0.5

  publish_rate_hz: 100

bottle_dummy:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "DUAL_XARM_V5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  # muscle_option: "ISAAC"
  muscle_option: "DUMMY"
  # muscle_option: "REAL_ROBOT"
  move_time_sec: 0.01       # mandatory setting for REAL_ROBOT
  min_move_time_sec: 0.01   # mandatory setting for REAL_ROBOT

  brain_registry:
    - "manual_adapter:MANUAL"
    - "random_brain_adapter:RANDOM"
    - "rosbag_player:ROSBAG"
    # - "external_control:DUMMY"

  rosbag_player:
    bag_path: "/home/rog-sf/ws/synapse_ws/src/synapse/resources/snack1.json"
    topic_component_map:
      - "/xarm7_left_controller/commands:left_arm"
      - "/xarm7_right_controller/commands:right_arm"
      - "/allegro_hand_position_effort_controller_l/commands:left_hand"
      - "/allegro_hand_position_effort_controller_r/commands:right_hand"
    seek_velocity: 0.2
    seek_min_duration: 0.5

  publish_rate_hz: 100

dual_arm:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "DUAL_PANDA"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20

  muscle_option: "ISAAC"
  brain_registry:
    - "manual_adapter:MANUAL"
  publish_rate_hz: 100

gr00t_franka_sim:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "SINGLE_PANDA_CAM"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "ISAAC"

  brain_registry:
    - "vla_franka:GR00T"
    - "manual_adapter:MANUAL"
  vla_franka:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  publish_rate_hz: 100

panda_v5:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "PANDA_V5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20

  muscle_option: "ISAAC"
  brain_registry:
    - "manual_adapter:MANUAL"
  publish_rate_hz: 100

multi_brain_test:
  # basic
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "SINGLE_PANDA_CAM"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20

  muscle_option: "ISAAC"

  # brain
  brain_registry:
    - "manual_adapter:MANUAL"
    - "vla_pick:GR00T"
    - "vla_place:GR00T"

  ## vla_pick
  vla_pick:
    policy_ip: "172.16.6.101"
    policy_port: "8888"
    default_command: "pick up the blue box"
  vla_place:
    policy_ip: "172.16.6.101"
    policy_port: "8889"
    default_command: "place the box on the tray"

  publish_rate_hz: 100

fr5_real:
  scenario_filename: "scn_v2.yaml"
  embodiment_name: "SINGLE_FR5"
  bt_tick_frequency_hz: 50
  obs_buffer_window_size: 20
  muscle_option: "REAL_ROBOT"

  brain_registry:
    - "manual_adapter:MANUAL"

  publish_rate_hz: 100
  
# rviz_test:
#   scenario_filename: "scn_v2.yaml"
#   embodiment_name: "SINGLE_FR5"
#   bt_tick_frequency_hz: 50
#   obs_buffer_window_size: 20

#   muscle_option: "RVIZ"

#   brain_registry:
#     - "manual_adapter:MANUAL"
#     - "rosbag_adapter:ROSBAG"
  
#   bag_path: "bag.rosbag"

#   vla_left:
#     policy_ip: "172.16.6.101"
#     policy_port: "8888"
#     default_command: "pick up the blue box"
#   publish_rate_hz: 100
