SINGLE_FR5:
  table_height: 0.85
  usd_filename: "fr5.usd"
  manipulator_step_size: 0.1   # for manual
  eef_step_size: 0.01           # for manual
  robots:
    fr5:
      prim_path: "/World/fairino5_v6"
      states: "/synapse/joint_states/fr5"
      yourdfpy_description: false
      urdf_filename: "fairino5_v6.urdf"
      components:
        arm:
          type: "manipulator"
          name: "fairino5_v6"
          joint_names: ["j1", "j2", "j3", "j4", "j5", "j6"]
          joint_indices: [0, 1, 2, 3, 4, 5]
          eef_frame: "wrist3_link"
          target:
            ISAAC: "/synapse/target"
            DUMMY: "/syanapse/target"

DUAL_XARM_V6:
  table_height: 0.85
  usd_filename: "dual_xarm7_v6.usd"
  manipulator_step_size: 0.1
  eef_step_size: 0.01
  robots:
    xarm_v6_right:
      prim_path: "/World/xarm7_v6r"
      urdf_filename: "xarm7_clean.urdf"
      yourdfpy_description: false
      states: "/synapse/joint_states/xarm_v6_right"
      components:
        right_arm:
          type: "manipulator"
          eef_frame: "link_eef"
          name: "xarm7_v6_right"
          joint_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6]
          target:
            ISAAC: "/synapse/target/right_arm"
            DUMMY: "/synapse/target/right_arm"
            REAL_ROBOT:
              topic: "/right_xarm7_traj_controller/joint_trajectory"
              msg_type: "JointTrajectory"
        right_hand:
          type: "end-effector"
          name: "allegro_v6_right"
          single_finger_dofs: 4
          joint_names: ["joint_00", "joint_10", "joint_20", "joint_30", "joint_40",
                        "joint_01", "joint_11", "joint_21", "joint_31", "joint_41",
                        "joint_02", "joint_12", "joint_22", "joint_32", "joint_42",
                        "joint_03", "joint_13", "joint_23", "joint_33", "joint_43"]
          joint_indices: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
          joint_limits:   # rad, [lower, upper]
            {joint_00: [-1.571, 0.0], joint_01: [-3.142, 0.0], joint_02: [-1.571, 0.0], joint_03: [-1.571, 0.0],
             joint_10: [-0.349, 1.571], joint_20: [-1.396, 1.396], joint_30: [-1.396, 0.349], joint_40: [-1.571, 0.349],
             joint_11: [0.0, 1.571], joint_21: [0.0, 1.571], joint_31: [0.0, 1.571], joint_41: [0.0, 1.571],
             joint_12: [0.0, 1.571], joint_22: [0.0, 1.571], joint_32: [0.0, 1.571], joint_42: [0.0, 1.571],
             joint_13: [0.0, 1.571], joint_23: [0.0, 1.571], joint_33: [0.0, 1.571], joint_43: [0.0, 1.571]}
          target:
            ISAAC: "/synapse/target/right_hand"
            DUMMY: "/synapse/target/right_hand"
            REAL_ROBOT: null

    xarm_v6_left:
      prim_path: "/World/xarm7_v6l"
      urdf_filename: "xarm7_clean.urdf"
      yourdfpy_description: false
      states: "/synapse/joint_states/xarm_v6_left"
      components:
        left_arm:
          type: "manipulator"
          eef_frame: "link_eef"
          name: "xarm7_v6_left"
          joint_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6]
          target:
            ISAAC: "/synapse/target/left_arm"
            DUMMY: "/synapse/target/left_arm"
            REAL_ROBOT:
              topic: "/left_xarm7_traj_controller/joint_trajectory"
              msg_type: "JointTrajectory"
        left_hand:
          type: "end-effector"
          name: "allegro_v6_left"
          single_finger_dofs: 4
          joint_names: ["joint_00", "joint_10", "joint_20", "joint_30", "joint_40",
                        "joint_01", "joint_11", "joint_21", "joint_31", "joint_41",
                        "joint_02", "joint_12", "joint_22", "joint_32", "joint_42",
                        "joint_03", "joint_13", "joint_23", "joint_33", "joint_43"]
          joint_indices: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
          joint_limits:   # rad, [lower, upper]
            {joint_00: [0.0, 1.571], joint_01: [0.0, 3.142], joint_02: [0.0, 1.571], joint_03: [0.0, 1.571],
             joint_10: [-1.571, 0.349], joint_20: [-1.396, 1.396], joint_30: [-0.349, 1.396], joint_40: [-0.349, 1.571],
             joint_11: [-1.571, 0.0], joint_21: [-1.571, 0.0], joint_31: [-1.571, 0.0], joint_41: [-1.571, 0.0],
             joint_12: [-1.571, 0.0], joint_22: [-1.571, 0.0], joint_32: [-1.571, 0.0], joint_42: [-1.571, 0.0],
             joint_13: [-1.571, 0.0], joint_23: [-1.571, 0.0], joint_33: [-1.571, 0.0], joint_43: [-1.571, 0.0]}
          target:
            ISAAC: "/synapse/target/left_hand"
            DUMMY: "/synapse/target/left_hand"
            REAL_ROBOT: null


DUAL_XARM_V5:
  # YUMI like mounting setting
  # right arm. pitch 60, yaw 30 := tilt 64.3, rotate 16.1
  # right arm. pitch 30, yaw 30 := tilt 41.4, rotate 40.9
  table_height: 0.85
  usd_filename: "dual_xarm7_v5_sense.usd"
  manipulator_step_size: 0.1   # for manual
  eef_step_size: 0.01           # for manual
  robots:
    dual_xarm_unit:                     # one physical articulation
      prim_path: "/Dual_Xarm7_v5_sense"
      urdf_filename: "dual_robot.urdf"
      yourdfpy_description: false
      states: "/synapse/joint_states/dual_xarm_unit"

      components:
        right_arm:
          type: "manipulator"
          eef_frame: "xarm_right_link_eef"
          name: "xarm7_v5_sense_right"
          joint_names: ["right_joint1", "right_joint2", "right_joint3", "right_joint4", "right_joint5", "right_joint6", "right_joint7"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6]
          target:
            ISAAC: "/synapse/target/right_arm"
            DUMMY: "/synapse/target/right_arm"
            REAL_ROBOT:
              topic: "/right_xarm7_traj_controller/joint_trajectory"
              msg_type: "JointTrajectory"

        left_arm:
          type: "manipulator"
          eef_frame: "xarm_left_link_eef"
          name: "xarm7_v5_sense_left"
          joint_names: ["left_joint1", "left_joint2", "left_joint3", "left_joint4", "left_joint5", "left_joint6", "left_joint7"]
          joint_indices: [7, 8, 9, 10, 11, 12, 13]
          target:
            ISAAC: "/synapse/target/left_arm"
            DUMMY: "/synapse/target/left_arm"
            REAL_ROBOT:
              topic: "/left_xarm7_traj_controller/joint_trajectory"
              msg_type: "JointTrajectory"

        right_hand:
          type: "end-effector"
          name: "v5_sense_right_with_collider"
          single_finger_dofs: 4
          joint_names: ["right_index_joint_0", "right_index_joint_1", "right_index_joint_2", "right_index_joint_3",
                "right_thumb_joint_0", "right_thumb_joint_1", "right_thumb_joint_2", "right_thumb_joint_3",
                "right_middle_joint_0", "right_middle_joint_1", "right_middle_joint_2", "right_middle_joint_3",
                "right_ring_joint_0", "right_ring_joint_1", "right_ring_joint_2", "right_ring_joint_3"]
          joint_indices: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
          target:
            ISAAC: "/synapse/target/right_hand"
            DUMMY: "/synapse/target/right_hand"
            REAL_ROBOT: null
        left_hand:
          type: "end-effector"
          name: "v5_sense_left_with_collider"
          single_finger_dofs: 4
          joint_names: ["left_joint_0_0", "left_joint_1_0", "left_joint_2_0", "left_joint_3_0",
                        "left_joint_4_0", "left_joint_5_0", "left_joint_6_0", "left_joint_7_0",
                        "left_joint_8_0", "left_joint_9_0", "left_joint_10_0", "left_joint_11_0",
                        "left_joint_12_0", "left_joint_13_0", "left_joint_14_0", "left_joint_15_0"]
          joint_indices: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]
          target:
            ISAAC: "/synapse/target/left_hand"
            DUMMY: "/synapse/target/left_hand"
            REAL_ROBOT: null

DUAL_PANDA:
  usd_filename: "dual_panda.usd"
  manipulator_step_size: 0.1   # for manual
  eef_step_size: 0.01           # for manual
  robots:
    panda_left:
      description_name: "panda_description"
      urdf_filename: "panda.urdf"
      yourdfpy_description: true
      prim_path: "/World/franka_left"
      states: "/synapse/joint_states/panda_left"
      components:
        left_arm:
          type: "manipulator"
          name: "franka_left"
          eef_frame: "panda_hand"
          joint_names: ["panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7", "panda_finger_joint1", "panda_finger_joint2"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8]
          target: 
            ISAAC: "/synapse/target/panda_left"
    panda_right:
      description_name: "panda_description"
      urdf_filename: "panda.urdf"
      yourdfpy_description: true
      prim_path: "/World/franka_right"
      states: "/synapse/joint_states/panda_right"
      components:
        right_arm:
          type: "manipulator"
          name: "franka_right"
          eef_frame: "panda_hand"
          joint_names: ["panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7", "panda_finger_joint1", "panda_finger_joint2"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8]
          target: 
            ISAAC: "/synapse/target/panda_right"

SINGLE_PANDA_CAM:
  table_height: 0.85
  cameras:
    wrist:
      topic: "/synapse/camera/wrist/image_raw"    # DEFAULT /synapse/camera/[camera_name:wrist]/image_raw
      prim_path: "/World/franka_set/Franka/panda/panda_hand/wrist_cam"
      focal_length: 1.5
      orientation: [0.0274, -0.0114, -0.0003, 0.9995]     #pitch -75, roll 180, yaw 0
      translation: [-0.1, 0.0, -0.05]
      width: 256
      height: 256
      frequency: 20
    quarter_view:
      topic: "/synapse/camera/quarter_view/image_raw"
      prim_path: "/World/franka_set/Azure/Camera"
      focal_length: 1.5
      width: 256
      height: 256
      frequency: 20
      clipping_near_distance: 0.01
      clipping_far_distance: 10.0

  usd_filename: "OXE.usd"
  robots:
    panda_arm:
      yourdfpy_description: true
      description_name: "panda_description"
      prim_path: "/World/franka_set/Franka/panda"
      states: "/synapse/joint_states/panda"
      components:
        arm:
          target:
            ISAAC: "/synapse/target/panda"
          name: "panda"
          type: "manipulator"
          eef_frame: "panda_hand"
          joint_names: ["panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7", "panda_finger_joint1", "panda_finger_joint2"]
          joint_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8]