scenario_name: "pilot"
# ===================================
# 🧠 ADAPTER REGSTRY
# ADAPTERS ARE REGISTERED IN CONFIG_MAIN.
# ====================================
# 🌲 BEHAVIOR TREE STRUCTURE
behavior_tree:
  type: "Sequence"
  name: "Root"
  children:
    - type: "Action"
      name: "initial"
      adapter: "manual_nav"
      success_condition: "cond_b"
    - type: "Selector"
      name: "pickup_the_thing"
      children:
      - type: "Action"
        name: "pickup_modelA"
        adapter: "vla_pick"
        success_condition: "cond_c"
        failure_condition: "cond_d"
      - type: "Action"
        name: "recovery"
        adapter: "manual_nav"
        success_condition: "cond_c"
    - type: "Action"
      name: "wrapup"
      adapter: "vla_place"
      success_condition: "cond_e"